-- MySQL Script generated by MySQL Workbench
-- Tue Jan 21 14:08:41 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema et85mzsa1tojmca9
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema et85mzsa1tojmca9
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `et85mzsa1tojmca9` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `et85mzsa1tojmca9` ;

-- -----------------------------------------------------
-- Table `et85mzsa1tojmca9`.`Countries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `et85mzsa1tojmca9`.`Countries` ;

CREATE TABLE IF NOT EXISTS `et85mzsa1tojmca9`.`Countries` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `currency` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `et85mzsa1tojmca9`.`Provinces`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `et85mzsa1tojmca9`.`Provinces` ;

CREATE TABLE IF NOT EXISTS `et85mzsa1tojmca9`.`Provinces` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `country_id` INT(11) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `country_id` (`country_id` ASC) VISIBLE,
  CONSTRAINT `Provinces_ibfk_1`
    FOREIGN KEY (`country_id`)
    REFERENCES `et85mzsa1tojmca9`.`Countries` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `et85mzsa1tojmca9`.`Cities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `et85mzsa1tojmca9`.`Cities` ;

CREATE TABLE IF NOT EXISTS `et85mzsa1tojmca9`.`Cities` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `province_id` INT(11) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `province_id` (`province_id` ASC) VISIBLE,
  CONSTRAINT `Cities_ibfk_1`
    FOREIGN KEY (`province_id`)
    REFERENCES `et85mzsa1tojmca9`.`Provinces` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `et85mzsa1tojmca9`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `et85mzsa1tojmca9`.`Users` ;

CREATE TABLE IF NOT EXISTS `et85mzsa1tojmca9`.`Users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `encrypted_pw` VARCHAR(255) NULL DEFAULT NULL,
  `emailaddress` VARCHAR(255) NULL DEFAULT NULL,
  `firstname` VARCHAR(255) NULL DEFAULT NULL,
  `lastname` VARCHAR(255) NULL DEFAULT NULL,
  `fullname` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `homecity_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `homecity_id` (`homecity_id` ASC) VISIBLE,
  CONSTRAINT `Users_ibfk_1`
    FOREIGN KEY (`homecity_id`)
    REFERENCES `et85mzsa1tojmca9`.`Cities` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `et85mzsa1tojmca9`.`Restaurant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `et85mzsa1tojmca9`.`Restaurant` ;

CREATE TABLE IF NOT EXISTS `et85mzsa1tojmca9`.`Restaurant` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `yelp_id` VARCHAR(255) NULL DEFAULT NULL,
  `rating` FLOAT NULL DEFAULT NULL,
  `price` VARCHAR(64) NULL DEFAULT NULL,
  `lon` FLOAT NULL DEFAULT NULL,
  `lat` FLOAT NULL DEFAULT NULL,
  `city_name` VARCHAR(255) NULL DEFAULT NULL,
  `address` VARCHAR(10000) NULL DEFAULT NULL,
  `website` VARCHAR(255) NULL DEFAULT NULL,
  `review_count` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 70
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `et85mzsa1tojmca9`.`Bucketlist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `et85mzsa1tojmca9`.`Bucketlist` ;

CREATE TABLE IF NOT EXISTS `et85mzsa1tojmca9`.`Bucketlist` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NULL DEFAULT NULL,
  `rest_id` INT(11) NULL DEFAULT NULL,
  `visited` TINYINT(1) NULL DEFAULT NULL,
  `added_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `user_review` VARCHAR(4000) NULL DEFAULT NULL,
  `user_rating` FLOAT NULL DEFAULT NULL,
  `date_visited` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `rest_id` (`rest_id` ASC) VISIBLE,
  CONSTRAINT `Bucketlist_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `et85mzsa1tojmca9`.`Users` (`id`),
  CONSTRAINT `Bucketlist_ibfk_2`
    FOREIGN KEY (`rest_id`)
    REFERENCES `et85mzsa1tojmca9`.`Restaurant` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 98
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `et85mzsa1tojmca9`.`Categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `et85mzsa1tojmca9`.`Categories` ;

CREATE TABLE IF NOT EXISTS `et85mzsa1tojmca9`.`Categories` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `alias` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `et85mzsa1tojmca9`.`Cuisine`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `et85mzsa1tojmca9`.`Cuisine` ;

CREATE TABLE IF NOT EXISTS `et85mzsa1tojmca9`.`Cuisine` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `rest_id` INT(11) NOT NULL,
  `alias` VARCHAR(255) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `rest_id` (`rest_id` ASC) VISIBLE,
  CONSTRAINT `Cuisine_ibfk_1`
    FOREIGN KEY (`rest_id`)
    REFERENCES `et85mzsa1tojmca9`.`Restaurant` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `et85mzsa1tojmca9`.`Image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `et85mzsa1tojmca9`.`Image` ;

CREATE TABLE IF NOT EXISTS `et85mzsa1tojmca9`.`Image` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NULL DEFAULT NULL,
  `rest_id` INT(11) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `img_location` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `rest_id` (`rest_id` ASC) VISIBLE,
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `Image_ibfk_1`
    FOREIGN KEY (`rest_id`)
    REFERENCES `et85mzsa1tojmca9`.`Restaurant` (`id`),
  CONSTRAINT `Image_ibfk_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `et85mzsa1tojmca9`.`Users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
