USE DATABASE et85mzsa1tojmca9;


INSERT INTO Categories(title,alias) VALUES ('African','african');
INSERT INTO Categories(title,alias) VALUES ('Senegalese','senegalese');
INSERT INTO Categories(title,alias) VALUES ('South African','southafrican');
INSERT INTO Categories(title,alias) VALUES ('American (New)','newamerican');
INSERT INTO Categories(title,alias) VALUES ('American (Traditional)','tradamerican');
INSERT INTO Categories(title,alias) VALUES ('Andalusian','andalusian');
INSERT INTO Categories(title,alias) VALUES ('Arabian','arabian');
INSERT INTO Categories(title,alias) VALUES ('Arab Pizza','arabpizza');
INSERT INTO Categories(title,alias) VALUES ('Argentine','argentine"');
INSERT INTO Categories(title,alias) VALUES ('Armenian','armenian');
INSERT INTO Categories(title,alias) VALUES ('Asian Fusion','asianfusion');
INSERT INTO Categories(title,alias) VALUES ('Asturian','asturian');
INSERT INTO Categories(title,alias) VALUES ('Australian','australian');
INSERT INTO Categories(title,alias) VALUES ('Austrian','austrian');
INSERT INTO Categories(title,alias) VALUES ('Baguettes','baguettes');
INSERT INTO Categories(title,alias) VALUES ('Bangladeshi','bangladeshi');
INSERT INTO Categories(title,alias) VALUES ('Barbeque','bbq');
INSERT INTO Categories(title,alias) VALUES ('Basque','basque');
INSERT INTO Categories(title,alias) VALUES ('Bavarian','bavarian');
INSERT INTO Categories(title,alias) VALUES ('Beer Garden','beergarden');
INSERT INTO Categories(title,alias) VALUES ('Beer Hall','beerhall');
INSERT INTO Categories(title,alias) VALUES ('Beisl','beisl');
INSERT INTO Categories(title,alias) VALUES ('Belgian','belgian');
INSERT INTO Categories(title,alias) VALUES ('Flemish','flemish');
INSERT INTO Categories(title,alias) VALUES ('Bistros','bistros');
INSERT INTO Categories(title,alias) VALUES ('Black Sea','blacksea"');
INSERT INTO Categories(title,alias) VALUES ('Brasseries','brasseries');
INSERT INTO Categories(title,alias) VALUES ('Brazilian','brazilian');
INSERT INTO Categories(title,alias) VALUES ('Brazilian Empanadas','brazilianempanadas');
INSERT INTO Categories(title,alias) VALUES ('Central Brazilian',NULL);
INSERT INTO Categories(title,alias) VALUES ('Northeastern Brazilian','northeasternbrazilian');
INSERT INTO Categories(title,alias) VALUES ('Northern Brazilian','northernbrazilian');
INSERT INTO Categories(title,alias) VALUES ('Rodizios','rodizios');
INSERT INTO Categories(title,alias) VALUES ('Breakfast & Brunch','breakfast_brunch');
INSERT INTO Categories(title,alias) VALUES ('Pancakes','pancakes');
INSERT INTO Categories(title,alias) VALUES ('British','british');
INSERT INTO Categories(title,alias) VALUES ('Buffets','buffets');
INSERT INTO Categories(title,alias) VALUES ('Bulgarian','bulgarian');
INSERT INTO Categories(title,alias) VALUES ('Burgers','burgers');
INSERT INTO Categories(title,alias) VALUES ('Burmese','burmese"');
INSERT INTO Categories(title,alias) VALUES ('Cafes','cafes');
INSERT INTO Categories(title,alias) VALUES ('Themed Cafes','themedcafes');
INSERT INTO Categories(title,alias) VALUES ('Cafeteria','cafeteria');
INSERT INTO Categories(title,alias) VALUES ('Cajun/Creole','cajun');
INSERT INTO Categories(title,alias) VALUES ('Cambodian','cambodian');
INSERT INTO Categories(title,alias) VALUES ('Canadian(New)','newcanadian');
INSERT INTO Categories(title,alias) VALUES ('Canteen','canteen');
INSERT INTO Categories(title,alias) VALUES ('Caribbean','caribbean');
INSERT INTO Categories(title,alias) VALUES ('Dominican','dominican');
INSERT INTO Categories(title,alias) VALUES ('Haitian','haitian');
INSERT INTO Categories(title,alias) VALUES ('Puerto Rican','puertorican');
INSERT INTO Categories(title,alias) VALUES ('Trinidadian','trinidadian');
INSERT INTO Categories(title,alias) VALUES ('Catalan','catalan');
INSERT INTO Categories(title,alias) VALUES ('Cheesesteaks','cheesesteaks');
INSERT INTO Categories(title,alias) VALUES ('Chicken Shop','chickenshop');
INSERT INTO Categories(title,alias) VALUES ('Chcicken Wings','chicken_wings');
INSERT INTO Categories(title,alias) VALUES ('Chilean','chilean');
INSERT INTO Categories(title,alias) VALUES ('Chinese','chinese');
INSERT INTO Categories(title,alias) VALUES ('Cantonese','cantonese');
INSERT INTO Categories(title,alias) VALUES ('Congee','congee');
INSERT INTO Categories(title,alias) VALUES ('Dim Sum','dimsum');
INSERT INTO Categories(title,alias) VALUES ('Fuzhou','fuzhou');
INSERT INTO Categories(title,alias) VALUES ('Hainan','hainan');
INSERT INTO Categories(title,alias) VALUES ('Hakka','hakka');
INSERT INTO Categories(title,alias) VALUES ('Henghwa','henghwa');
INSERT INTO Categories(title,alias) VALUES ('Hokkien','hokkien');
INSERT INTO Categories(title,alias) VALUES ('Hunan','hunan');
INSERT INTO Categories(title,alias) VALUES ('Pekinese','pekinese');
INSERT INTO Categories(title,alias) VALUES ('Shanghainese','shanghainese');
INSERT INTO Categories(title,alias) VALUES ('Szechuan','szechua');
INSERT INTO Categories(title,alias) VALUES ('Teoche','teochew');
INSERT INTO Categories(title,alias) VALUES ('Comfort Food','comfortfood');
INSERT INTO Categories(title,alias) VALUES ('Corsica','corsican');
INSERT INTO Categories(title,alias) VALUES ('Creperies','creperies');
INSERT INTO Categories(title,alias) VALUES ('Cuban','cuban');
INSERT INTO Categories(title,alias) VALUES ('Curry Sausage','currysausage');
INSERT INTO Categories(title,alias) VALUES ('Cypriot','cypriot');
INSERT INTO Categories(title,alias) VALUES ('Czech','czech');
INSERT INTO Categories(title,alias) VALUES ('Czech/Slovakian','czechslovakia');
INSERT INTO Categories(title,alias) VALUES ('Danish','danish');
INSERT INTO Categories(title,alias) VALUES ('Delis','delis');
INSERT INTO Categories(title,alias) VALUES ('Diners','diners');
INSERT INTO Categories(title,alias) VALUES ('Dinner Theater','dinnertheater');
INSERT INTO Categories(title,alias) VALUES ('Dumplings','dumplings');
INSERT INTO Categories(title,alias) VALUES ('Eastern European','eastern_european');
INSERT INTO Categories(title,alias) VALUES ('Eritrean','eritrean');
INSERT INTO Categories(title,alias) VALUES ('Ethiopian','ethiopian');
INSERT INTO Categories(title,alias) VALUES ('Fast Food','hotdogs');
INSERT INTO Categories(title,alias) VALUES ('Filipino','filipino');
INSERT INTO Categories(title,alias) VALUES ('Fischbroetchen','fischbroetchen');
INSERT INTO Categories(title,alias) VALUES ('Fish & Chips','fishnchips');
INSERT INTO Categories(title,alias) VALUES ('Flatbread','flatbread');
INSERT INTO Categories(title,alias) VALUES ('Fondue','fondue');
INSERT INTO Categories(title,alias) VALUES ('Food Court','food_court');
INSERT INTO Categories(title,alias) VALUES ('Food Stands','foodstands');
INSERT INTO Categories(title,alias) VALUES ('Freiduria','freiduria"');
INSERT INTO Categories(title,alias) VALUES ('French','french');
INSERT INTO Categories(title,alias) VALUES ('Alsatian','alsatian');
INSERT INTO Categories(title,alias) VALUES ('Auvergnat','auvergnat');
INSERT INTO Categories(title,alias) VALUES ('Berrichon','berrichon,');
INSERT INTO Categories(title,alias) VALUES ('Bourguignon','bourguignon');
INSERT INTO Categories(title,alias) VALUES ('Mauritius','mauritius');
INSERT INTO Categories(title,alias) VALUES ('Nicoise','nicois');
INSERT INTO Categories(title,alias) VALUES ('Provencal','provencal');
INSERT INTO Categories(title,alias) VALUES ('Reunion','reunion');
INSERT INTO Categories(title,alias) VALUES ('French Southwest','sud_ouest,');
INSERT INTO Categories(title,alias) VALUES ('Galician','galician');
INSERT INTO Categories(title,alias) VALUES ('Game Meat','gamemeat');
INSERT INTO Categories(title,alias) VALUES ('Gastropubs','gastropubs');
INSERT INTO Categories(title,alias) VALUES ('Georgian','georgian');
INSERT INTO Categories(title,alias) VALUES ('German','german');
INSERT INTO Categories(title,alias) VALUES ('Baden','baden');
INSERT INTO Categories(title,alias) VALUES ('Eastern German','easterngerman');
INSERT INTO Categories(title,alias) VALUES ('Franconian','franconian');
INSERT INTO Categories(title,alias) VALUES ('Hessian','hessian');
INSERT INTO Categories(title,alias) VALUES ('Northern','German');
INSERT INTO Categories(title,alias) VALUES ('Palatine','palatine');
INSERT INTO Categories(title,alias) VALUES ('Rhinelandian','rhinelandian');
INSERT INTO Categories(title,alias) VALUES ('Giblets','giblets');
INSERT INTO Categories(title,alias) VALUES ('Gluten-Free','gluten_free');
INSERT INTO Categories(title,alias) VALUES ('Greek','greek');
INSERT INTO Categories(title,alias) VALUES ('Guamanian','guamanian');
INSERT INTO Categories(title,alias) VALUES ('Halal','halal');
INSERT INTO Categories(title,alias) VALUES ('Hawaiian','hawaiian');
INSERT INTO Categories(title,alias) VALUES ('Heuriger','heuriger');
INSERT INTO Categories(title,alias) VALUES ('Himalayan/Nepalese','''himalayan"');
INSERT INTO Categories(title,alias) VALUES ('Honduran','honduran');
INSERT INTO Categories(title,alias) VALUES ('Hong Kong Style Caf�','hkcafe');
INSERT INTO Categories(title,alias) VALUES ('Hot Dogs','hotdog');
INSERT INTO Categories(title,alias) VALUES ('Hot Pot','hotpot');
INSERT INTO Categories(title,alias) VALUES ('Hungarian','hungarian');
INSERT INTO Categories(title,alias) VALUES ('Iberian','iberian');
INSERT INTO Categories(title,alias) VALUES ('Indian','indpak');
INSERT INTO Categories(title,alias) VALUES ('Indonesian','indonesian,');
INSERT INTO Categories(title,alias) VALUES ('International','international');
INSERT INTO Categories(title,alias) VALUES ('Irish','irish');
INSERT INTO Categories(title,alias) VALUES ('Island Pub','island_pub,');
INSERT INTO Categories(title,alias) VALUES ('Israeli','israeli,');
INSERT INTO Categories(title,alias) VALUES ('Italian','italian');
INSERT INTO Categories(title,alias) VALUES ('Abruzzese','abruzzese');
INSERT INTO Categories(title,alias) VALUES ('Altoatesine','altoatesine');
INSERT INTO Categories(title,alias) VALUES ('Apulian','apulian');
INSERT INTO Categories(title,alias) VALUES ('Calabrian','calabrian');
INSERT INTO Categories(title,alias) VALUES ('Cucina campana','cucinacampana');
INSERT INTO Categories(title,alias) VALUES ('Emilian','emilian,');
INSERT INTO Categories(title,alias) VALUES ('Friulan','friulan,');
INSERT INTO Categories(title,alias) VALUES ('Ligurian','''ligurian"');
INSERT INTO Categories(title,alias) VALUES ('Lumbard','lumbard');
INSERT INTO Categories(title,alias) VALUES ('Napoletana','napoletana');
INSERT INTO Categories(title,alias) VALUES ('Piemonte','piemonte');
INSERT INTO Categories(title,alias) VALUES ('Roman','roman');
INSERT INTO Categories(title,alias) VALUES ('Sardinian','sardinian');
INSERT INTO Categories(title,alias) VALUES ('Sicilian','sicilian');
INSERT INTO Categories(title,alias) VALUES ('Tuscan','tuscan');
INSERT INTO Categories(title,alias) VALUES ('Venetian','venetian');
INSERT INTO Categories(title,alias) VALUES ('Japanese','apanese');
INSERT INTO Categories(title,alias) VALUES ('Blowfish','blowfish');
INSERT INTO Categories(title,alias) VALUES ('Conveyor Belt Sushi','conveyorsushi');
INSERT INTO Categories(title,alias) VALUES ('Donburi','donburi');
INSERT INTO Categories(title,alias) VALUES ('Gyudon','gyudon');
INSERT INTO Categories(title,alias) VALUES ('Oyakodon','oyakodon');
INSERT INTO Categories(title,alias) VALUES ('Hand Rolls','handrolls');
INSERT INTO Categories(title,alias) VALUES ('Horumon','horumon');
INSERT INTO Categories(title,alias) VALUES ('Izakaya','izakaya');
INSERT INTO Categories(title,alias) VALUES ('Japanese Curry','japacurry');
INSERT INTO Categories(title,alias) VALUES ('Kaiseki','kaiseki');
INSERT INTO Categories(title,alias) VALUES ('Kushikatsu','kushikatsu,');
INSERT INTO Categories(title,alias) VALUES ('Oden','oden');
INSERT INTO Categories(title,alias) VALUES ('Okinawan','okinawan');
INSERT INTO Categories(title,alias) VALUES ('Okonomiyaki','okonomiyaki,');
INSERT INTO Categories(title,alias) VALUES ('Onigiri','onigiri');
INSERT INTO Categories(title,alias) VALUES ('Ramen','ramen, All');
INSERT INTO Categories(title,alias) VALUES ('Robatayaki','robatayaki');
INSERT INTO Categories(title,alias) VALUES ('Soba','soba');
INSERT INTO Categories(title,alias) VALUES ('Sukiyaki','sukiyaki');
INSERT INTO Categories(title,alias) VALUES ('Takoyaki','takoyaki');
INSERT INTO Categories(title,alias) VALUES ('Tempura','empura');
INSERT INTO Categories(title,alias) VALUES ('Teppanyaki','teppanyaki');
INSERT INTO Categories(title,alias) VALUES ('Tonkatsu','tonkatsu');
INSERT INTO Categories(title,alias) VALUES ('Udon','udon,');
INSERT INTO Categories(title,alias) VALUES ('Unagi','unagi');
INSERT INTO Categories(title,alias) VALUES ('Western Style Japanese Food','westernjapanese');
INSERT INTO Categories(title,alias) VALUES ('Yakiniku','yakiniku');
INSERT INTO Categories(title,alias) VALUES ('Yakitori','yakitori');
INSERT INTO Categories(title,alias) VALUES ('Jewish','jewish');
INSERT INTO Categories(title,alias) VALUES ('Kebab','kebab,');
INSERT INTO Categories(title,alias) VALUES ('Kopitiam','kopitiam');
INSERT INTO Categories(title,alias) VALUES ('Korean','korean');
INSERT INTO Categories(title,alias) VALUES ('Kosher','kosher');
INSERT INTO Categories(title,alias) VALUES ('Kurdish','kurdish');
INSERT INTO Categories(title,alias) VALUES ('Laos','laos');
INSERT INTO Categories(title,alias) VALUES ('Laotian','Laotian');
INSERT INTO Categories(title,alias) VALUES ('Latin American','latin');
INSERT INTO Categories(title,alias) VALUES ('Colombian','colombian');
INSERT INTO Categories(title,alias) VALUES ('Salvadoran','salvadoran');
INSERT INTO Categories(title,alias) VALUES ('Venezuelan','venezuelan');
INSERT INTO Categories(title,alias) VALUES ('Live/Raw Food','raw_food');
INSERT INTO Categories(title,alias) VALUES ('Lyonnais','Lyonnais');
INSERT INTO Categories(title,alias) VALUES ('Malaysian','malaysian');
INSERT INTO Categories(title,alias) VALUES ('Mamak','mamak');
INSERT INTO Categories(title,alias) VALUES ('Nyonya','nyonya');
INSERT INTO Categories(title,alias) VALUES ('Meatballs','meatballs');
INSERT INTO Categories(title,alias) VALUES ('Mediterranean','mediterranean');
INSERT INTO Categories(title,alias) VALUES ('Falafel','falafel');
INSERT INTO Categories(title,alias) VALUES ('Mexican','mexican');
INSERT INTO Categories(title,alias) VALUES ('Eastern Mexican','easternmexican');
INSERT INTO Categories(title,alias) VALUES ('Jaliscan','jaliscan,');
INSERT INTO Categories(title,alias) VALUES ('Northern Mexican','northernmexican');
INSERT INTO Categories(title,alias) VALUES ('Oaxacan','oaxacan');
INSERT INTO Categories(title,alias) VALUES ('Pueblan','pueblan');
INSERT INTO Categories(title,alias) VALUES ('Tacos','tacos');
INSERT INTO Categories(title,alias) VALUES ('Tamales','tamales');
INSERT INTO Categories(title,alias) VALUES ('Yucatan','yucatan');
INSERT INTO Categories(title,alias) VALUES ('Middle Eastern','mideastern');
INSERT INTO Categories(title,alias) VALUES ('Egyptian','egyptian,');
INSERT INTO Categories(title,alias) VALUES ('Lebanese','lebanese');
INSERT INTO Categories(title,alias) VALUES ('Milk Bars','milkbars');
INSERT INTO Categories(title,alias) VALUES ('Modern Australian','modern_australian,');
INSERT INTO Categories(title,alias) VALUES ('Modern European','modern_european');
INSERT INTO Categories(title,alias) VALUES ('Mongolian','mongolian');
INSERT INTO Categories(title,alias) VALUES ('Moroccan','moroccan');
INSERT INTO Categories(title,alias) VALUES ('New Mexican Cuisine','newmexican');
INSERT INTO Categories(title,alias) VALUES ('New Zealand','newzealand');
INSERT INTO Categories(title,alias) VALUES ('Nicaraguan','nicaraguan');
INSERT INTO Categories(title,alias) VALUES ('Night Food','nightfood');
INSERT INTO Categories(title,alias) VALUES ('Nikkei','nikkei,');
INSERT INTO Categories(title,alias) VALUES ('Noodles','noodles,');
INSERT INTO Categories(title,alias) VALUES ('Norcinerie','norcinerie');
INSERT INTO Categories(title,alias) VALUES ('Open Sandwiches','opensandwiches');
INSERT INTO Categories(title,alias) VALUES ('Oriental','oriental');
INSERT INTO Categories(title,alias) VALUES ('PF/Comercial','pfcomercial');
INSERT INTO Categories(title,alias) VALUES ('Pakistani','pakistani');
INSERT INTO Categories(title,alias) VALUES ('Pan Asian','panasian');
INSERT INTO Categories(title,alias) VALUES ('Parent Cafes','eltern_cafes');
INSERT INTO Categories(title,alias) VALUES ('Parma','parma,');
INSERT INTO Categories(title,alias) VALUES ('Persian/Iranian','persian');
INSERT INTO Categories(title,alias) VALUES ('Peruvian','peruvian');
INSERT INTO Categories(title,alias) VALUES ('Pita','pita,');
INSERT INTO Categories(title,alias) VALUES ('Pizza','pizza,');
INSERT INTO Categories(title,alias) VALUES ('Polish','polish,');
INSERT INTO Categories(title,alias) VALUES ('Pierogis','pierogis,');
INSERT INTO Categories(title,alias) VALUES ('Polynesian','polynesian,');
INSERT INTO Categories(title,alias) VALUES ('Pop-Up Restaurants','popuprestaurants,');
INSERT INTO Categories(title,alias) VALUES ('Portuguese','portuguese');
INSERT INTO Categories(title,alias) VALUES ('Alentejo','alentejo');
INSERT INTO Categories(title,alias) VALUES ('Algarve','algarve,');
INSERT INTO Categories(title,alias) VALUES ('Azores','azores,');
INSERT INTO Categories(title,alias) VALUES ('Beira','beira,');
INSERT INTO Categories(title,alias) VALUES ('Fado Houses','fado_houses');
INSERT INTO Categories(title,alias) VALUES ('Madeira','madeira');
INSERT INTO Categories(title,alias) VALUES ('Minho','minho');
INSERT INTO Categories(title,alias) VALUES ('Ribatejo','ribatejo');
INSERT INTO Categories(title,alias) VALUES ('Tras-os-Montes','tras_os_montes');
INSERT INTO Categories(title,alias) VALUES ('Potatoes','potatoes');
INSERT INTO Categories(title,alias) VALUES ('Poutineries','poutineries');
INSERT INTO Categories(title,alias) VALUES ('Pub Food','pubfood');
INSERT INTO Categories(title,alias) VALUES ('Rice','riceshop');
INSERT INTO Categories(title,alias) VALUES ('Romanian','romanian');
INSERT INTO Categories(title,alias) VALUES ('Rotisserie Chicken','otisserie_chicken');
INSERT INTO Categories(title,alias) VALUES ('Russian','russian');
INSERT INTO Categories(title,alias) VALUES ('Salad','salad');
INSERT INTO Categories(title,alias) VALUES ('Schnitzel','schnitzel');
INSERT INTO Categories(title,alias) VALUES ('Scottish','scottish');
INSERT INTO Categories(title,alias) VALUES ('Seafood','seafood');
INSERT INTO Categories(title,alias) VALUES ('Serbo Croatian','serbocroatian');
INSERT INTO Categories(title,alias) VALUES ('Signature Cuisine','signature_cuisine');
INSERT INTO Categories(title,alias) VALUES ('Singaporean','singaporean');
INSERT INTO Categories(title,alias) VALUES ('Slovakian','slovakian');
INSERT INTO Categories(title,alias) VALUES ('Somali','somali');
INSERT INTO Categories(title,alias) VALUES ('Soul Food','soulfood');
INSERT INTO Categories(title,alias) VALUES ('Soup','soup');
INSERT INTO Categories(title,alias) VALUES ('Southern','southern');
INSERT INTO Categories(title,alias) VALUES ('Spanish','spanish');
INSERT INTO Categories(title,alias) VALUES ('Arroceria / Paella','arroceria_paella');
INSERT INTO Categories(title,alias) VALUES ('Sri Lankan','srilankan');
INSERT INTO Categories(title,alias) VALUES ('Steakhouses','steak');
INSERT INTO Categories(title,alias) VALUES ('Supper Clubs','supperclubs');
INSERT INTO Categories(title,alias) VALUES ('Sushi Bars','sushi');
INSERT INTO Categories(title,alias) VALUES ('Swabian','swabian');
INSERT INTO Categories(title,alias) VALUES ('Swedish','Swedish');
INSERT INTO Categories(title,alias) VALUES ('Swiss Food','swissfood');
INSERT INTO Categories(title,alias) VALUES ('Syrian','syrian');
INSERT INTO Categories(title,alias) VALUES ('Tabernas','tabernas');
INSERT INTO Categories(title,alias) VALUES ('Taiwanese','taiwanese');
INSERT INTO Categories(title,alias) VALUES ('Tapas/Small Plates','tapasmallplates');
INSERT INTO Categories(title,alias) VALUES ('Tavola Calda','tavolacalda');
INSERT INTO Categories(title,alias) VALUES ('Tex-Mex','tex-mex');
INSERT INTO Categories(title,alias) VALUES ('Thai','thai');
INSERT INTO Categories(title,alias) VALUES ('Traditional Norwegian','norwegian,');
INSERT INTO Categories(title,alias) VALUES ('Traditional Swedish','traditional_swedish');
INSERT INTO Categories(title,alias) VALUES ('Trattorie','trattorie');
INSERT INTO Categories(title,alias) VALUES ('Turkish','Turkish');
INSERT INTO Categories(title,alias) VALUES ('Chee Kufta','cheekufta');
INSERT INTO Categories(title,alias) VALUES ('Gozleme','gozleme');
INSERT INTO Categories(title,alias) VALUES ('Homemade Food','homemadefood');
INSERT INTO Categories(title,alias) VALUES ('Lahmacun','lahmacun');
INSERT INTO Categories(title,alias) VALUES ('Ottoman Cuisine','ottomancuisine');
INSERT INTO Categories(title,alias) VALUES ('Turkish Ravioli','turkishravioli');
INSERT INTO Categories(title,alias) VALUES ('Uzbek','uzbe');
INSERT INTO Categories(title,alias) VALUES ('Vegan','vegan');
INSERT INTO Categories(title,alias) VALUES ('Vegetarian','vegetarian');
INSERT INTO Categories(title,alias) VALUES ('Venison','venison');
INSERT INTO Categories(title,alias) VALUES ('Vietnamese','vietnamese');
INSERT INTO Categories(title,alias) VALUES ('Waffles','waffles');
INSERT INTO Categories(title,alias) VALUES ('Wok','wok');
INSERT INTO Categories(title,alias) VALUES ('Wraps','wraps');
INSERT INTO Categories(title,alias) VALUES ('Yugoslav','yugoslav');